name: Trigger auto deployment for aca-apl2003

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-apl2003-AutoDeployTrigger-c079d6d1-8699-4cbd-a17e-3a6a9b17a749.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACAAPL2003_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAAPL2003_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAAPL2003_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrapl2003rvd16jun.azurecr.io
          registryUsername: ${{ secrets.ACAAPL2003_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAAPL2003_REGISTRY_PASSWORD }}
          containerAppName: aca-apl2003
          resourceGroup: RG1
          imageToBuild: acrapl2003rvd16jun.azurecr.io/aca-apl2003:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


